Point task2 = new Point(8, 6);
Fraction tries = new Fraction(6, 5);
Fraction second = new Fraction(9, 15);
Console.WriteLine(tries.ToString(second));
int b = 5;
int a = 3;
b = -b;
a = a;
Console.WriteLine(b);
Console.WriteLine(a);
